import type { CSSProperties } from "react";

export const styles = {
  launcherRoot: {
    position: "fixed",
    right: 24,
    bottom: 24,
    zIndex: 1000,
    maxWidth: "calc(100vw - 32px)",
  },
  launcher: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    padding: 6,
    height: 44,
    borderRadius: 999,
    background: "var(--color-card)",
    border: "1px solid var(--color-border)",
    boxShadow: "0 18px 44px rgba(15,23,42,0.18)",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    transition:
      "width 0.7s cubic-bezier(0.16, 1, 0.3, 1), padding 0.7s cubic-bezier(0.16, 1, 0.3, 1), gap 0.7s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  launcherCollapsed: {
    width: 44,
    height: 44,
    padding: 6,
    gap: 0,
    overflow: "hidden",
    justifyContent: "center",
  },
  launcherIcon: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "#164734",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    border: 0,
    cursor: "pointer",
    padding: 0,
  },
  launcherInputWrap: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    maxWidth: 400,
    opacity: 1,
    transition: "max-width 0.7s cubic-bezier(0.16, 1, 0.3, 1) 0.1s, opacity 0.1s ease",
  },

  launcherInputWrapCollapsed: {
    maxWidth: 0,
    opacity: 0,
    pointerEvents: "none",
  },
  launcherInput: {
    flex: 1,
    minWidth: 0,
    height: 34,
    border: 0,
    outline: "none",
    background: "transparent",
    color: "var(--color-foreground)",
    fontSize: 13.5,
    fontFamily: "inherit",
  },
  launcherButton: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: 0,
    background: "#164734",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  pageRoot: {
    height: "calc(100vh - 44px)",
    background: "var(--color-background)",
    borderTop: "1px solid var(--color-border)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "12px 14px 18px",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    overflow: "hidden",
  },
  pageTitleBar: {
    width: "min(1180px, 100%)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 2px 12px",
    flexShrink: 0,
  },
  pageWorkspace: {
    width: "min(1180px, 100%)",
    minHeight: 0,
    flex: 1,
    display: "grid",
    gridTemplateColumns: "260px minmax(0, 1fr)",
    gap: 14,
  },
  chatPanel: {
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: "var(--color-background)",
    overflow: "hidden",
    borderRadius: 16,
    border: "1px solid var(--color-border)",
    boxShadow: "0 22px 60px rgba(15,23,42,0.10)",
  },
  pageShell: {
    width: "min(1180px, 100%)",
    minHeight: "calc(100vh - 76px)",
    display: "grid",
    gridTemplateColumns: "260px minmax(0, 1fr)",
    overflow: "hidden",
    borderRadius: 16,
    background: "var(--color-card)",
    border: "1px solid var(--color-border)",
    boxShadow: "0 22px 60px rgba(15,23,42,0.10)",
  },
  chatHeader: {
    minHeight: 58,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 16px",
    borderBottom: "1px solid var(--color-border)",
    background: "var(--color-card)",
    flexShrink: 0,
  },
  chatHeaderText: {
    minWidth: 0,
    flex: 1,
  },
  pageHeader: {
    display: "flex",
    alignItems: "center",
    gap: 13,
    padding: "18px 20px",
    borderBottom: "1px solid var(--color-border)",
    background: "var(--color-card)",
  },
  pageAvatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: "#164734",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pageTitle: {
    margin: 0,
    color: "var(--color-card-foreground)",
    fontSize: 18,
    lineHeight: 1.2,
    fontWeight: 720,
  },
  pageSubtitle: {
    margin: "3px 0 0",
    color: "var(--color-muted-foreground)",
    fontSize: 13,
    lineHeight: 1.35,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
    marginLeft: "auto",
  },
  loadPane: {
    padding: "14px 18px",
    borderBottom: "1px solid var(--color-border)",
    background: "var(--color-muted)",
    display: "flex",
    flexDirection: "column",
    gap: 9,
  },
  loadHeader: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    color: "var(--color-foreground)",
    fontSize: 12.5,
    fontWeight: 650,
  },
  progressTrack: {
    height: 5,
    background: "rgba(22,71,52,0.12)",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressLabel: {
    fontSize: 11.5,
    color: "var(--color-muted-foreground)",
    textAlign: "right",
  },
  chatBody: {
    minHeight: 0,
    flex: 1,
    display: "grid",
    gridTemplateColumns: "240px minmax(0, 1fr)",
    background: "var(--color-background)",
  },
  historyRail: {
    minHeight: 0,
    background: "var(--color-card)",
    border: "1px solid var(--color-border)",
    borderRadius: 16,
    boxShadow: "0 18px 48px rgba(15,23,42,0.08)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  historyHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 12px 8px",
    color: "var(--color-muted-foreground)",
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 8,
    border: "1px solid var(--color-border)",
    background: "var(--color-background)",
    color: "var(--color-foreground)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  historyList: {
    minHeight: 0,
    overflowY: "auto",
    padding: "0 8px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  emptyHistory: {
    padding: 10,
    color: "var(--color-muted-foreground)",
    fontSize: 12.5,
  },
  historyItemWrap: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    borderRadius: 10,
    border: "1px solid transparent",
  },
  activeHistoryItemWrap: {
    borderColor: "rgba(73,119,40,0.35)",
    background: "rgba(73,119,40,0.08)",
  },
  historyItem: {
    minWidth: 0,
    flex: 1,
    border: 0,
    background: "transparent",
    color: "var(--color-foreground)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 6px",
    textAlign: "left",
  },
  historyText: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  historyTitle: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 12.5,
    fontWeight: 650,
  },
  historyPreview: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--color-muted-foreground)",
    fontSize: 11.5,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#22c55e",
    flexShrink: 0,
  },
  deleteHistoryButton: {
    width: 26,
    height: 26,
    border: 0,
    background: "transparent",
    color: "var(--color-muted-foreground)",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pageMessages: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "20px 24px 24px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    background: "var(--color-background)",
  },
  messageGroup: {
    display: "flex",
    flexDirection: "column",
    maxWidth: "min(680px, 86%)",
  },
  messageAuthor: {
    fontSize: 11,
    color: "var(--color-muted-foreground)",
    marginBottom: 5,
    padding: "0 2px",
  },
  messageBubble: {
    padding: "11px 14px",
    borderRadius: 14,
    fontSize: 14,
    lineHeight: 1.55,
    whiteSpace: "normal",
    wordBreak: "break-word",
  },
  userBubble: {
    background: "#164734",
    color: "#fff",
    borderBottomRightRadius: 5,
  },
  assistantBubble: {
    background: "var(--color-card)",
    color: "var(--color-card-foreground)",
    border: "1px solid var(--color-border)",
    borderBottomLeftRadius: 5,
  },
  messageActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  inlineActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    margin: "8px 0 10px",
  },
  markdownBlock: {
    display: "block",
  },
  markdownParagraph: {
    margin: "0 0 10px",
  },
  markdownHeading: {
    margin: "4px 0 8px",
    fontSize: 14,
    fontWeight: 720,
    color: "var(--color-card-foreground)",
  },
  orderedList: {
    margin: "0 0 10px 18px",
    padding: 0,
  },
  unorderedList: {
    margin: "0 0 10px 18px",
    padding: 0,
  },
  listItem: {
    margin: "0 0 6px",
    paddingLeft: 2,
  },
  inlineCode: {
    borderRadius: 5,
    background: "var(--color-muted)",
    color: "#164734",
    padding: "1px 4px",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "0.92em",
  },
  actionButton: {
    border: "1px solid rgba(22,71,52,0.16)",
    background: "var(--color-card)",
    color: "#164734",
    borderRadius: 999,
    padding: "7px 10px",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    fontWeight: 650,
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  primaryActionButton: {
    background: "#164734",
    borderColor: "#164734",
    color: "#fff",
  },
  typingRow: {
    display: "flex",
    gap: 4,
    alignItems: "center",
    padding: "4px 0",
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#a8b3ac",
  },
  pageInputRow: {
    padding: "14px 16px",
    borderTop: "1px solid var(--color-border)",
    background: "var(--color-card)",
    display: "flex",
    gap: 10,
    alignItems: "flex-end",
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: "#164734",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "opacity 0.15s, transform 0.12s",
  },
  gpuWarning: {
    margin: "14px 18px 0",
    padding: "10px 13px",
    background: "var(--color-muted)",
    color: "#8a5a06",
    borderRadius: 9,
    fontSize: 12.5,
    lineHeight: 1.45,
  },
  pageTextarea: {
    flex: 1,
    resize: "none",
    border: "1px solid var(--color-border)",
    borderRadius: 14,
    padding: "10px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    background: "var(--color-background)",
    color: "var(--color-foreground)",
    lineHeight: 1.5,
    minHeight: 40,
    maxHeight: 140,
    outline: "none",
  },
} satisfies Record<string, CSSProperties>;
